version: '2.3'
services:

  hashview:
    container_name: hashview
    build: .
    # Uncomment this if you use nvidia-docker2
    # See https://github.com/NVIDIA/nvidia-docker
    runtime: nvidia
    environment:
      - TZ=America/Toronto
    ports:
      - "4567:4567"
    networks:
      - hashview

  db:
    container_name: db
    image: mysql:5.7
    #command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
    networks:
      - hashview

networks:
  hashview:


